version: "3.7"

services:
  app:
    image: "voting"
    build:
      context: .
    container_name: "voting_app"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - static_data:/app/staticfiles
    env_file:
      - ./.env
      - ./.env.db
    depends_on:
      - db
  db:
    image: "postgres:12-alpine"
    container_name: "voting_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db

volumes:
  postgres_data:
  static_data:
