apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  resources:
    - name: git-repo-resource
      type: git
    - name: target-image-resource
      type: image
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
  tasks:
    - name: build-image
      taskRef:
        name: build-image
      resources:
        inputs:
          - name: git-source
            resource: git-repo-resource
        outputs:
          - name: built-image
            resource: target-image-resource
    - name: apply-manifests
      taskRef:
        name: apply-manifests
      resources:
        inputs:
          - name: source
            resource: git-repo-resource
      runAfter:
        - build-image
    - name: update-deployment
      taskRef:
        name: update-deployment
      resources:
        inputs:
          - name: image
            resource: target-image-resource
      params:
        - name: deployment
          value: $(params.deployment-name)
      runAfter:
        - apply-manifests
