apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: cicd-voting-image
spec:
  type: image
  params:
    - name: url
      value: "ghcr.io/cpoenisch/cicd-voting:tekton"
    - name: digest
      value:
